service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: eu-west-2

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  scraper:
    name: dataVisTopicScraper
    handler: scraper.handler
    description: scrape data vis topics
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!package-lock.json"
        - "!package.json"